insert into "Photo" (user_id, photo_name) values (333, 'Crake, african black');
insert into "Photo" (user_id, photo_name) values (940, 'Capuchin, weeper');
insert into "Photo" (user_id, photo_name) values (920, 'Deer, black-tailed');
insert into "Photo" (user_id, photo_name) values (9, 'Caribou');
insert into "Photo" (user_id, photo_name) values (376, 'European spoonbill');
insert into "Photo" (user_id, photo_name) values (943, 'Black-tailed deer');
insert into "Photo" (user_id, photo_name) values (596, 'Woodpecker, red-headed');
insert into "Photo" (user_id, photo_name) values (630, 'Crane, sarus');
insert into "Photo" (user_id, photo_name) values (762, 'Lion, south american sea');
insert into "Photo" (user_id, photo_name) values (474, 'Greater adjutant stork');
insert into "Photo" (user_id, photo_name) values (450, 'Monkey, bleeding heart');
insert into "Photo" (user_id, photo_name) values (280, 'Barking gecko');
insert into "Photo" (user_id, photo_name) values (433, 'Red-necked phalarope');
insert into "Photo" (user_id, photo_name) values (929, 'Swallow-tail gull');
insert into "Photo" (user_id, photo_name) values (968, 'Sage hen');
insert into "Photo" (user_id, photo_name) values (479, 'Pied kingfisher');
insert into "Photo" (user_id, photo_name) values (265, 'Common nighthawk');
insert into "Photo" (user_id, photo_name) values (904, 'Onager');
insert into "Photo" (user_id, photo_name) values (359, 'Squirrel, nelson ground');
insert into "Photo" (user_id, photo_name) values (931, 'Seal, northern elephant');
insert into "Photo" (user_id, photo_name) values (535, 'Brush-tailed bettong');
insert into "Photo" (user_id, photo_name) values (515, 'Sugar glider');
insert into "Photo" (user_id, photo_name) values (394, 'Shrike, common boubou');
insert into "Photo" (user_id, photo_name) values (712, 'Eastern box turtle');
insert into "Photo" (user_id, photo_name) values (774, 'Blesbok');
insert into "Photo" (user_id, photo_name) values (979, 'Gulls (unidentified)');
insert into "Photo" (user_id, photo_name) values (355, 'Malagasy ground boa');
insert into "Photo" (user_id, photo_name) values (392, 'Bear, american black');
insert into "Photo" (user_id, photo_name) values (663, 'Dragon, komodo');
insert into "Photo" (user_id, photo_name) values (745, 'Barrows goldeneye');
insert into "Photo" (user_id, photo_name) values (674, 'Common shelduck');
insert into "Photo" (user_id, photo_name) values (735, 'Vervet monkey');
insert into "Photo" (user_id, photo_name) values (159, 'Scarlet macaw');
insert into "Photo" (user_id, photo_name) values (449, 'Fork-tailed drongo');
insert into "Photo" (user_id, photo_name) values (438, 'Pintail, bahama');
insert into "Photo" (user_id, photo_name) values (125, 'Kangaroo, western grey');
insert into "Photo" (user_id, photo_name) values (52, 'Desert kangaroo rat');
insert into "Photo" (user_id, photo_name) values (232, 'Asian red fox');
insert into "Photo" (user_id, photo_name) values (988, 'Common zorro');
insert into "Photo" (user_id, photo_name) values (848, 'Heron, yellow-crowned night');
insert into "Photo" (user_id, photo_name) values (249, 'Laughing dove');
insert into "Photo" (user_id, photo_name) values (674, 'Asian elephant');
insert into "Photo" (user_id, photo_name) values (838, 'Green-winged macaw');
insert into "Photo" (user_id, photo_name) values (8, 'Common long-nosed armadillo');
insert into "Photo" (user_id, photo_name) values (202, 'White-lipped peccary');
insert into "Photo" (user_id, photo_name) values (70, 'Lion, south american sea');
insert into "Photo" (user_id, photo_name) values (82, 'Lesser double-collared sunbird');
insert into "Photo" (user_id, photo_name) values (775, 'Rattlesnake, dusky');
insert into "Photo" (user_id, photo_name) values (704, 'Roller, lilac-breasted');
insert into "Photo" (user_id, photo_name) values (661, 'Nilgai');
insert into "Photo" (user_id, photo_name) values (771, 'Striped skunk');
insert into "Photo" (user_id, photo_name) values (787, 'Kalahari scrub robin');
insert into "Photo" (user_id, photo_name) values (547, 'Sheep, red');
insert into "Photo" (user_id, photo_name) values (998, 'Nighthawk, common');
insert into "Photo" (user_id, photo_name) values (172, 'Admiral, indian red');
insert into "Photo" (user_id, photo_name) values (347, 'Alligator, american');
insert into "Photo" (user_id, photo_name) values (195, 'Dingo');
insert into "Photo" (user_id, photo_name) values (382, 'Goose, cereopsis');
insert into "Photo" (user_id, photo_name) values (435, 'Kudu, greater');
insert into "Photo" (user_id, photo_name) values (326, 'American marten');
insert into "Photo" (user_id, photo_name) values (690, 'Capuchin, brown');
insert into "Photo" (user_id, photo_name) values (992, 'Bat, madagascar fruit');
insert into "Photo" (user_id, photo_name) values (207, 'Ibis, glossy');
insert into "Photo" (user_id, photo_name) values (283, 'Common nighthawk');
insert into "Photo" (user_id, photo_name) values (132, 'Eastern fox squirrel');
insert into "Photo" (user_id, photo_name) values (967, 'Groundhog');
insert into "Photo" (user_id, photo_name) values (209, 'Hyena, spotted');
insert into "Photo" (user_id, photo_name) values (973, 'Eurasian badger');
insert into "Photo" (user_id, photo_name) values (128, 'Zebra, common');
insert into "Photo" (user_id, photo_name) values (413, 'Arctic fox');
insert into "Photo" (user_id, photo_name) values (137, 'Vulture, bengal');
insert into "Photo" (user_id, photo_name) values (133, 'Stick insect');
insert into "Photo" (user_id, photo_name) values (823, 'Tyrant flycatcher');
insert into "Photo" (user_id, photo_name) values (138, 'Civet (unidentified)');
insert into "Photo" (user_id, photo_name) values (807, 'Lizard, collared');
insert into "Photo" (user_id, photo_name) values (703, 'Lappet-faced vulture');
insert into "Photo" (user_id, photo_name) values (647, 'Giant heron');
insert into "Photo" (user_id, photo_name) values (122, 'Musk ox');
insert into "Photo" (user_id, photo_name) values (729, 'Russian dragonfly');
insert into "Photo" (user_id, photo_name) values (758, 'Squirrel, palm');
insert into "Photo" (user_id, photo_name) values (20, 'Bear, grizzly');
insert into "Photo" (user_id, photo_name) values (971, 'Duck, comb');
insert into "Photo" (user_id, photo_name) values (83, 'Australian spiny anteater');
insert into "Photo" (user_id, photo_name) values (638, 'Horned puffin');
insert into "Photo" (user_id, photo_name) values (579, 'Albatross, galapagos');
insert into "Photo" (user_id, photo_name) values (858, 'Waved albatross');
insert into "Photo" (user_id, photo_name) values (679, 'Magpie, black-backed');
insert into "Photo" (user_id, photo_name) values (137, 'Black-eyed bulbul');
insert into "Photo" (user_id, photo_name) values (169, 'North American porcupine');
insert into "Photo" (user_id, photo_name) values (68, 'Legaan, water');
insert into "Photo" (user_id, photo_name) values (619, 'Weaver, lesser masked');
insert into "Photo" (user_id, photo_name) values (296, 'Baboon, olive');
insert into "Photo" (user_id, photo_name) values (227, 'Grenadier, purple');
insert into "Photo" (user_id, photo_name) values (769, 'Phalarope, northern');
insert into "Photo" (user_id, photo_name) values (79, 'Eagle, pallas''s fish');
insert into "Photo" (user_id, photo_name) values (521, 'Northern elephant seal');
insert into "Photo" (user_id, photo_name) values (764, 'Least chipmunk');
insert into "Photo" (user_id, photo_name) values (250, 'Snake (unidentified)');
insert into "Photo" (user_id, photo_name) values (452, 'Four-horned antelope');
insert into "Photo" (user_id, photo_name) values (123, 'Gecko, bent-toed');
insert into "Photo" (user_id, photo_name) values (487, 'Ferruginous hawk');
insert into "Photo" (user_id, photo_name) values (894, 'Gull, southern black-backed');
insert into "Photo" (user_id, photo_name) values (200, 'Snow goose');
insert into "Photo" (user_id, photo_name) values (652, 'Black-capped chickadee');
insert into "Photo" (user_id, photo_name) values (767, 'Brazilian tapir');
insert into "Photo" (user_id, photo_name) values (43, 'Water monitor');
insert into "Photo" (user_id, photo_name) values (412, 'Cape white-eye');
insert into "Photo" (user_id, photo_name) values (471, 'Bulbul, african red-eyed');
insert into "Photo" (user_id, photo_name) values (112, 'Woylie');
insert into "Photo" (user_id, photo_name) values (673, 'White-headed vulture');
insert into "Photo" (user_id, photo_name) values (695, 'Lion, galapagos sea');
insert into "Photo" (user_id, photo_name) values (46, 'Eastern diamondback rattlesnake');
insert into "Photo" (user_id, photo_name) values (342, 'Yellow-rumped siskin');
insert into "Photo" (user_id, photo_name) values (320, 'Groundhog');
insert into "Photo" (user_id, photo_name) values (748, 'Egret, snowy');
insert into "Photo" (user_id, photo_name) values (126, 'Rhinoceros, black');
insert into "Photo" (user_id, photo_name) values (816, 'Black-tailed deer');
insert into "Photo" (user_id, photo_name) values (124, 'Wild water buffalo');
insert into "Photo" (user_id, photo_name) values (277, 'Deer, barasingha');
insert into "Photo" (user_id, photo_name) values (757, 'Squirrel glider');
insert into "Photo" (user_id, photo_name) values (373, 'Monitor, white-throated');
insert into "Photo" (user_id, photo_name) values (51, 'Tortoise, desert');
insert into "Photo" (user_id, photo_name) values (983, 'Sloth, two-toed');
insert into "Photo" (user_id, photo_name) values (52, 'Tarantula');
insert into "Photo" (user_id, photo_name) values (792, 'Burrowing owl');
insert into "Photo" (user_id, photo_name) values (713, 'Lemming, arctic');
insert into "Photo" (user_id, photo_name) values (252, 'Crow, american');
insert into "Photo" (user_id, photo_name) values (25, 'Penguin, fairy');
insert into "Photo" (user_id, photo_name) values (119, 'Thrasher, curve-billed');
insert into "Photo" (user_id, photo_name) values (494, 'Turkey, australian brush');
insert into "Photo" (user_id, photo_name) values (384, 'Sea birds (unidentified)');
insert into "Photo" (user_id, photo_name) values (381, 'Phalarope, red-necked');
insert into "Photo" (user_id, photo_name) values (393, 'Yak');
insert into "Photo" (user_id, photo_name) values (503, 'Australian magpie');
insert into "Photo" (user_id, photo_name) values (208, 'Purple moorhen');
insert into "Photo" (user_id, photo_name) values (263, 'Stork, openbill');
insert into "Photo" (user_id, photo_name) values (703, 'Bear, polar');
insert into "Photo" (user_id, photo_name) values (796, 'Frilled dragon');
insert into "Photo" (user_id, photo_name) values (238, 'Gull, dusky');
insert into "Photo" (user_id, photo_name) values (826, 'Puma, south american');
insert into "Photo" (user_id, photo_name) values (723, 'Osprey');
insert into "Photo" (user_id, photo_name) values (441, 'Stork, openbill');
insert into "Photo" (user_id, photo_name) values (658, 'Seven-banded armadillo');
insert into "Photo" (user_id, photo_name) values (192, 'Bird, secretary');
insert into "Photo" (user_id, photo_name) values (919, 'American black bear');
insert into "Photo" (user_id, photo_name) values (368, 'Squirrel, indian giant');
insert into "Photo" (user_id, photo_name) values (518, 'Heron, yellow-crowned night');
insert into "Photo" (user_id, photo_name) values (497, 'Hawk-headed parrot');
insert into "Photo" (user_id, photo_name) values (903, 'Andean goose');
insert into "Photo" (user_id, photo_name) values (106, 'Blacksmith plover');
insert into "Photo" (user_id, photo_name) values (799, 'Vulture, white-rumped');
insert into "Photo" (user_id, photo_name) values (371, 'Chital');
insert into "Photo" (user_id, photo_name) values (664, 'Little brown bat');
insert into "Photo" (user_id, photo_name) values (201, 'Cobra, cape');
insert into "Photo" (user_id, photo_name) values (514, 'Polecat, african');
insert into "Photo" (user_id, photo_name) values (415, 'Pigeon, wood');
insert into "Photo" (user_id, photo_name) values (486, 'Waved albatross');
insert into "Photo" (user_id, photo_name) values (738, 'Quoll, eastern');
insert into "Photo" (user_id, photo_name) values (523, 'Stork, greater adjutant');
insert into "Photo" (user_id, photo_name) values (302, 'Jaguar');
insert into "Photo" (user_id, photo_name) values (472, 'Lion, mountain');
insert into "Photo" (user_id, photo_name) values (588, 'Gemsbok');
insert into "Photo" (user_id, photo_name) values (24, 'Buffalo, african');
insert into "Photo" (user_id, photo_name) values (913, 'Alligator, mississippi');
insert into "Photo" (user_id, photo_name) values (521, 'Swan, black');
insert into "Photo" (user_id, photo_name) values (322, 'Bird (unidentified)');
insert into "Photo" (user_id, photo_name) values (968, 'Kalahari scrub robin');
insert into "Photo" (user_id, photo_name) values (562, 'Deer, swamp');
insert into "Photo" (user_id, photo_name) values (272, 'Rainbow lory');
insert into "Photo" (user_id, photo_name) values (340, 'Savanna fox');
insert into "Photo" (user_id, photo_name) values (361, 'Shrike, crimson-breasted');
insert into "Photo" (user_id, photo_name) values (683, 'Great cormorant');
insert into "Photo" (user_id, photo_name) values (771, 'Moorhen, purple');
insert into "Photo" (user_id, photo_name) values (165, 'Malabar squirrel');
insert into "Photo" (user_id, photo_name) values (702, 'Leopard');
insert into "Photo" (user_id, photo_name) values (606, 'Buffalo, american');
insert into "Photo" (user_id, photo_name) values (408, 'Ground monitor (unidentified)');
insert into "Photo" (user_id, photo_name) values (999, 'Lizard (unidentified)');
insert into "Photo" (user_id, photo_name) values (322, 'Red-tailed wambenger');
insert into "Photo" (user_id, photo_name) values (840, 'African ground squirrel (unidentified)');
insert into "Photo" (user_id, photo_name) values (467, 'White-headed vulture');
insert into "Photo" (user_id, photo_name) values (381, 'Porcupine, crested');
insert into "Photo" (user_id, photo_name) values (385, 'Grey-footed squirrel');
insert into "Photo" (user_id, photo_name) values (520, 'Boat-billed heron');
insert into "Photo" (user_id, photo_name) values (679, 'Caracal');
insert into "Photo" (user_id, photo_name) values (710, 'Jabiru stork');
insert into "Photo" (user_id, photo_name) values (66, 'Squirrel glider');
insert into "Photo" (user_id, photo_name) values (364, 'Tortoise, desert');
insert into "Photo" (user_id, photo_name) values (947, 'Hottentot teal');
insert into "Photo" (user_id, photo_name) values (237, 'Polecat, african');
insert into "Photo" (user_id, photo_name) values (435, 'Sambar');
insert into "Photo" (user_id, photo_name) values (203, 'Tortoise, radiated');
insert into "Photo" (user_id, photo_name) values (684, 'Sage grouse');
insert into "Photo" (user_id, photo_name) values (10, 'Cormorant (unidentified)');
insert into "Photo" (user_id, photo_name) values (599, 'Pig-tailed macaque');
insert into "Photo" (user_id, photo_name) values (562, 'Northern fur seal');
insert into "Photo" (user_id, photo_name) values (247, 'Cat, toddy');
insert into "Photo" (user_id, photo_name) values (726, 'Kiskadee, great');
insert into "Photo" (user_id, photo_name) values (455, 'Lemming, collared');
insert into "Photo" (user_id, photo_name) values (979, 'Yellow-crowned night heron');
insert into "Photo" (user_id, photo_name) values (830, 'Starling, greater blue-eared');
insert into "Photo" (user_id, photo_name) values (376, 'Phascogale, red-tailed');
insert into "Photo" (user_id, photo_name) values (899, 'Lion, galapagos sea');
insert into "Photo" (user_id, photo_name) values (861, 'Lark, horned');
insert into "Photo" (user_id, photo_name) values (726, 'Great skua');
insert into "Photo" (user_id, photo_name) values (504, 'Blue shark');
insert into "Photo" (user_id, photo_name) values (384, 'Goldeneye, common');
insert into "Photo" (user_id, photo_name) values (538, 'Bushbaby, large-eared');
insert into "Photo" (user_id, photo_name) values (856, 'Nelson ground squirrel');
insert into "Photo" (user_id, photo_name) values (617, 'Lion, steller''s sea');
insert into "Photo" (user_id, photo_name) values (988, 'Phascogale, brush-tailed');
insert into "Photo" (user_id, photo_name) values (940, 'Elephant, asian');
insert into "Photo" (user_id, photo_name) values (312, 'Shrike, southern white-crowned');
insert into "Photo" (user_id, photo_name) values (355, 'Two-banded monitor');
insert into "Photo" (user_id, photo_name) values (780, 'Cockatoo, long-billed');
insert into "Photo" (user_id, photo_name) values (358, 'Ostrich');
insert into "Photo" (user_id, photo_name) values (568, 'Wombat, common');
insert into "Photo" (user_id, photo_name) values (298, 'Horned lark');
insert into "Photo" (user_id, photo_name) values (882, 'Snowy owl');
insert into "Photo" (user_id, photo_name) values (78, 'Duiker, common');
insert into "Photo" (user_id, photo_name) values (65, 'Elegant crested tinamou');
insert into "Photo" (user_id, photo_name) values (135, 'Guerza');
insert into "Photo" (user_id, photo_name) values (505, 'Dabchick');
insert into "Photo" (user_id, photo_name) values (745, 'Caiman, spectacled');
insert into "Photo" (user_id, photo_name) values (334, 'Dabchick');
insert into "Photo" (user_id, photo_name) values (918, 'Red-breasted cockatoo');
insert into "Photo" (user_id, photo_name) values (632, 'Snowy owl');
insert into "Photo" (user_id, photo_name) values (605, 'Brown pelican');
insert into "Photo" (user_id, photo_name) values (96, 'Starling, superb');
insert into "Photo" (user_id, photo_name) values (765, 'Goose, cape barren');
insert into "Photo" (user_id, photo_name) values (182, 'Great skua');
insert into "Photo" (user_id, photo_name) values (607, 'Cobra (unidentified)');
insert into "Photo" (user_id, photo_name) values (626, 'Deer, black-tailed');
insert into "Photo" (user_id, photo_name) values (91, 'Black swan');
insert into "Photo" (user_id, photo_name) values (760, 'Laughing kookaburra');
insert into "Photo" (user_id, photo_name) values (808, 'Stork, openbill');
insert into "Photo" (user_id, photo_name) values (337, 'Mongoose, small indian');
insert into "Photo" (user_id, photo_name) values (245, 'Saddle-billed stork');
insert into "Photo" (user_id, photo_name) values (529, 'Frogmouth, tawny');
insert into "Photo" (user_id, photo_name) values (396, 'Spur-winged goose');
insert into "Photo" (user_id, photo_name) values (170, 'Cormorant, javanese');
insert into "Photo" (user_id, photo_name) values (263, 'Cat, ringtail');
insert into "Photo" (user_id, photo_name) values (295, 'Goat, mountain');
insert into "Photo" (user_id, photo_name) values (266, 'Armadillo, common long-nosed');
insert into "Photo" (user_id, photo_name) values (841, 'Mandras tree shrew');
insert into "Photo" (user_id, photo_name) values (954, 'Yellow-throated sandgrouse');
insert into "Photo" (user_id, photo_name) values (253, 'Hartebeest, coke''s');
insert into "Photo" (user_id, photo_name) values (188, 'Mouse, four-striped grass');
insert into "Photo" (user_id, photo_name) values (143, 'Miner''s cat');
insert into "Photo" (user_id, photo_name) values (786, 'Hoffman''s sloth');
insert into "Photo" (user_id, photo_name) values (419, 'Denham''s bustard');
insert into "Photo" (user_id, photo_name) values (37, 'Two-toed sloth');
insert into "Photo" (user_id, photo_name) values (845, 'House sparrow');
insert into "Photo" (user_id, photo_name) values (808, 'North American beaver');
insert into "Photo" (user_id, photo_name) values (997, 'Paradoxure');
insert into "Photo" (user_id, photo_name) values (972, 'Dove, white-winged');
insert into "Photo" (user_id, photo_name) values (634, 'Spurfowl, yellow-necked');
insert into "Photo" (user_id, photo_name) values (875, 'Crow, pied');
insert into "Photo" (user_id, photo_name) values (384, 'Rhesus macaque');
insert into "Photo" (user_id, photo_name) values (378, 'Ring-tailed gecko');
insert into "Photo" (user_id, photo_name) values (306, 'Indian red admiral');
insert into "Photo" (user_id, photo_name) values (588, 'African lion');
insert into "Photo" (user_id, photo_name) values (194, 'Bushbuck');
insert into "Photo" (user_id, photo_name) values (310, 'Bear, black');
insert into "Photo" (user_id, photo_name) values (843, 'Mockingbird, galapagos');
insert into "Photo" (user_id, photo_name) values (418, 'Snake (unidentified)');
insert into "Photo" (user_id, photo_name) values (945, 'Long-nosed bandicoot');
insert into "Photo" (user_id, photo_name) values (421, 'Lemur, ring-tailed');
insert into "Photo" (user_id, photo_name) values (987, 'Boa, columbian rainbow');
insert into "Photo" (user_id, photo_name) values (779, 'Fox, savanna');
insert into "Photo" (user_id, photo_name) values (395, 'Bandicoot, short-nosed');
insert into "Photo" (user_id, photo_name) values (95, 'Flamingo, greater');
insert into "Photo" (user_id, photo_name) values (644, 'Coke''s hartebeest');
insert into "Photo" (user_id, photo_name) values (361, 'Weaver, lesser masked');
insert into "Photo" (user_id, photo_name) values (796, 'Dama wallaby');
insert into "Photo" (user_id, photo_name) values (56, 'Black-cheeked waxbill');
insert into "Photo" (user_id, photo_name) values (340, 'Hartebeest, coke''s');
insert into "Photo" (user_id, photo_name) values (386, 'American badger');
insert into "Photo" (user_id, photo_name) values (511, 'North American river otter');
insert into "Photo" (user_id, photo_name) values (449, 'Savanna fox');
insert into "Photo" (user_id, photo_name) values (601, 'Turkey, common');
insert into "Photo" (user_id, photo_name) values (295, 'Red and blue macaw');
insert into "Photo" (user_id, photo_name) values (810, 'Ring-tailed gecko');
insert into "Photo" (user_id, photo_name) values (654, 'Greater rhea');
insert into "Photo" (user_id, photo_name) values (783, 'Tiger snake');
insert into "Photo" (user_id, photo_name) values (927, 'Hyrax');
insert into "Photo" (user_id, photo_name) values (782, 'Viper, egyptian');
insert into "Photo" (user_id, photo_name) values (132, 'Dama wallaby');
insert into "Photo" (user_id, photo_name) values (305, 'Great egret');
insert into "Photo" (user_id, photo_name) values (617, 'Anteater, giant');
insert into "Photo" (user_id, photo_name) values (811, 'Long-necked turtle');
insert into "Photo" (user_id, photo_name) values (213, 'Lion, mountain');
insert into "Photo" (user_id, photo_name) values (934, 'Painted stork');
insert into "Photo" (user_id, photo_name) values (88, 'Albatross, galapagos');
insert into "Photo" (user_id, photo_name) values (243, 'Bontebok');
insert into "Photo" (user_id, photo_name) values (919, 'Wood pigeon');
insert into "Photo" (user_id, photo_name) values (735, 'Civet (unidentified)');
insert into "Photo" (user_id, photo_name) values (844, 'Eagle, tawny');
insert into "Photo" (user_id, photo_name) values (260, 'Agile wallaby');
insert into "Photo" (user_id, photo_name) values (467, 'Horned puffin');
insert into "Photo" (user_id, photo_name) values (576, 'Shark, blue');
insert into "Photo" (user_id, photo_name) values (122, 'Mudskipper (unidentified)');
insert into "Photo" (user_id, photo_name) values (829, 'Bird (unidentified)');
insert into "Photo" (user_id, photo_name) values (59, 'Bennett''s wallaby');
insert into "Photo" (user_id, photo_name) values (346, 'Partridge, coqui');
insert into "Photo" (user_id, photo_name) values (759, 'Feral rock pigeon');
insert into "Photo" (user_id, photo_name) values (311, 'Frilled lizard');
insert into "Photo" (user_id, photo_name) values (387, 'Cougar');
insert into "Photo" (user_id, photo_name) values (545, 'Macaque, bonnet');
insert into "Photo" (user_id, photo_name) values (990, 'Turkey vulture');
insert into "Photo" (user_id, photo_name) values (934, 'Adouri (unidentified)');
insert into "Photo" (user_id, photo_name) values (467, 'Tailless tenrec');
insert into "Photo" (user_id, photo_name) values (523, 'Emerald green tree boa');
insert into "Photo" (user_id, photo_name) values (184, 'Ox, musk');
insert into "Photo" (user_id, photo_name) values (729, 'Blue-breasted cordon bleu');
insert into "Photo" (user_id, photo_name) values (927, 'Pheasant, ring-necked');
insert into "Photo" (user_id, photo_name) values (546, 'Tern, white-winged');
insert into "Photo" (user_id, photo_name) values (6, 'Iguana, land');
insert into "Photo" (user_id, photo_name) values (470, 'Native cat');
insert into "Photo" (user_id, photo_name) values (684, 'Sage grouse');
insert into "Photo" (user_id, photo_name) values (628, 'Flightless cormorant');
insert into "Photo" (user_id, photo_name) values (559, 'Blue wildebeest');
insert into "Photo" (user_id, photo_name) values (514, 'Crab, sally lightfoot');
insert into "Photo" (user_id, photo_name) values (284, 'Pale white-eye');
insert into "Photo" (user_id, photo_name) values (341, 'Osprey');
insert into "Photo" (user_id, photo_name) values (454, 'Bottle-nose dolphin');
insert into "Photo" (user_id, photo_name) values (576, 'Bird, secretary');
insert into "Photo" (user_id, photo_name) values (772, 'Langur, common');
insert into "Photo" (user_id, photo_name) values (99, 'Cattle egret');
insert into "Photo" (user_id, photo_name) values (761, 'Woodpecker, red-headed');
insert into "Photo" (user_id, photo_name) values (964, 'Ocelot');
insert into "Photo" (user_id, photo_name) values (892, 'Plover, blacksmith');
insert into "Photo" (user_id, photo_name) values (642, 'Sage grouse');
insert into "Photo" (user_id, photo_name) values (594, 'Whale, baleen');
insert into "Photo" (user_id, photo_name) values (150, 'Australian magpie');
insert into "Photo" (user_id, photo_name) values (365, 'Long-finned pilot whale');
insert into "Photo" (user_id, photo_name) values (617, 'Hedgehog, south african');
insert into "Photo" (user_id, photo_name) values (580, 'Porcupine, north american');
insert into "Photo" (user_id, photo_name) values (886, 'Wallaby, whip-tailed');
insert into "Photo" (user_id, photo_name) values (838, 'Knob-nosed goose');
insert into "Photo" (user_id, photo_name) values (137, 'Gazelle, thomson''s');
insert into "Photo" (user_id, photo_name) values (261, 'Common waterbuck');
insert into "Photo" (user_id, photo_name) values (865, 'European red squirrel');
insert into "Photo" (user_id, photo_name) values (416, 'Llama');
insert into "Photo" (user_id, photo_name) values (4, 'Northern fur seal');
insert into "Photo" (user_id, photo_name) values (638, 'Screamer, southern');
insert into "Photo" (user_id, photo_name) values (892, 'Magnificent frigate bird');
insert into "Photo" (user_id, photo_name) values (173, 'Puma, south american');
insert into "Photo" (user_id, photo_name) values (962, 'Stanley bustard');
insert into "Photo" (user_id, photo_name) values (917, 'Topi');
insert into "Photo" (user_id, photo_name) values (290, 'Vervet monkey');
insert into "Photo" (user_id, photo_name) values (488, 'Red-shouldered glossy starling');
insert into "Photo" (user_id, photo_name) values (704, 'Ringtail');
insert into "Photo" (user_id, photo_name) values (869, 'Snake, green vine');
insert into "Photo" (user_id, photo_name) values (870, 'Black spider monkey');
insert into "Photo" (user_id, photo_name) values (82, 'Cow, scottish highland');
insert into "Photo" (user_id, photo_name) values (326, 'Puku');
insert into "Photo" (user_id, photo_name) values (320, 'White-lipped peccary');
insert into "Photo" (user_id, photo_name) values (736, 'Black-cheeked waxbill');
insert into "Photo" (user_id, photo_name) values (875, 'Native cat');
insert into "Photo" (user_id, photo_name) values (129, 'Sportive lemur');
insert into "Photo" (user_id, photo_name) values (592, 'Starling, superb');
insert into "Photo" (user_id, photo_name) values (255, 'Cattle egret');
insert into "Photo" (user_id, photo_name) values (760, 'Wambenger, red-tailed');
insert into "Photo" (user_id, photo_name) values (839, 'Fox, cape');
insert into "Photo" (user_id, photo_name) values (435, 'Brown pelican');
insert into "Photo" (user_id, photo_name) values (100, 'Barbet, levaillant''s');
insert into "Photo" (user_id, photo_name) values (360, 'Buffalo, american');
insert into "Photo" (user_id, photo_name) values (929, 'Anteater, australian spiny');
insert into "Photo" (user_id, photo_name) values (267, 'Australian sea lion');
insert into "Photo" (user_id, photo_name) values (482, 'Common rhea');
insert into "Photo" (user_id, photo_name) values (764, 'Bee-eater, white-fronted');
insert into "Photo" (user_id, photo_name) values (731, 'Prehensile-tailed porcupine');
insert into "Photo" (user_id, photo_name) values (974, 'Shrike, crimson-breasted');
insert into "Photo" (user_id, photo_name) values (979, 'Asian false vampire bat');
insert into "Photo" (user_id, photo_name) values (532, 'Bat-eared fox');
insert into "Photo" (user_id, photo_name) values (889, 'Chital');
insert into "Photo" (user_id, photo_name) values (146, 'Drongo, fork-tailed');
insert into "Photo" (user_id, photo_name) values (651, 'Plover, three-banded');
insert into "Photo" (user_id, photo_name) values (656, 'Bennett''s wallaby');
insert into "Photo" (user_id, photo_name) values (1000, 'Andean goose');
insert into "Photo" (user_id, photo_name) values (142, 'Pronghorn');
insert into "Photo" (user_id, photo_name) values (336, 'Brush-tailed rat kangaroo');
insert into "Photo" (user_id, photo_name) values (379, 'Colobus, black and white');
insert into "Photo" (user_id, photo_name) values (678, 'Bear, black');
insert into "Photo" (user_id, photo_name) values (132, 'Coatimundi, white-nosed');
insert into "Photo" (user_id, photo_name) values (792, 'Jungle cat');
insert into "Photo" (user_id, photo_name) values (524, 'Heron, grey');
insert into "Photo" (user_id, photo_name) values (891, 'Trumpeter swan');
insert into "Photo" (user_id, photo_name) values (1000, 'Butterfly, canadian tiger swallowtail');
insert into "Photo" (user_id, photo_name) values (950, 'Mudskipper (unidentified)');
insert into "Photo" (user_id, photo_name) values (770, 'African elephant');
insert into "Photo" (user_id, photo_name) values (724, 'Gazer, sun');
insert into "Photo" (user_id, photo_name) values (610, 'Curve-billed thrasher');
insert into "Photo" (user_id, photo_name) values (996, 'Tree porcupine');
insert into "Photo" (user_id, photo_name) values (346, 'Toucan, red-billed');
insert into "Photo" (user_id, photo_name) values (300, 'Mongoose, banded');
insert into "Photo" (user_id, photo_name) values (371, 'Skink, blue-tongued');
insert into "Photo" (user_id, photo_name) values (218, 'Stork, marabou');
insert into "Photo" (user_id, photo_name) values (151, 'Little brown dove');
insert into "Photo" (user_id, photo_name) values (734, 'Sloth, pale-throated three-toed');
insert into "Photo" (user_id, photo_name) values (770, 'Caiman, spectacled');
insert into "Photo" (user_id, photo_name) values (475, 'Plains zebra');
insert into "Photo" (user_id, photo_name) values (703, 'Black-capped capuchin');
insert into "Photo" (user_id, photo_name) values (367, 'Boa, emerald green tree');
insert into "Photo" (user_id, photo_name) values (725, 'Vulture, lappet-faced');
insert into "Photo" (user_id, photo_name) values (748, 'Sable antelope');
insert into "Photo" (user_id, photo_name) values (57, 'Crane, stanley');
insert into "Photo" (user_id, photo_name) values (855, 'Screamer, crested');
insert into "Photo" (user_id, photo_name) values (275, 'Boubou, southern');
insert into "Photo" (user_id, photo_name) values (137, 'Baleen whale');
insert into "Photo" (user_id, photo_name) values (772, 'Hyena, striped');
insert into "Photo" (user_id, photo_name) values (766, 'Thrasher, curve-billed');
insert into "Photo" (user_id, photo_name) values (109, 'Jaguarundi');
insert into "Photo" (user_id, photo_name) values (616, 'Great skua');
insert into "Photo" (user_id, photo_name) values (452, 'Galapagos tortoise');
insert into "Photo" (user_id, photo_name) values (147, 'Stork, european');
insert into "Photo" (user_id, photo_name) values (169, 'Northern fur seal');
insert into "Photo" (user_id, photo_name) values (167, 'Lion, south american sea');
insert into "Photo" (user_id, photo_name) values (722, 'Long-tailed jaeger');
insert into "Photo" (user_id, photo_name) values (823, 'Snowy owl');
insert into "Photo" (user_id, photo_name) values (154, 'Macaw, red and blue');
insert into "Photo" (user_id, photo_name) values (133, 'African ground squirrel (unidentified)');
insert into "Photo" (user_id, photo_name) values (59, 'Waved albatross');
insert into "Photo" (user_id, photo_name) values (72, 'Indian mynah');
insert into "Photo" (user_id, photo_name) values (62, 'Hornbill, southern ground');
insert into "Photo" (user_id, photo_name) values (34, 'Lion, california sea');
insert into "Photo" (user_id, photo_name) values (604, 'Wambenger, red-tailed');
insert into "Photo" (user_id, photo_name) values (423, 'Netted rock dragon');
insert into "Photo" (user_id, photo_name) values (866, 'Slender loris');
insert into "Photo" (user_id, photo_name) values (53, 'Common long-nosed armadillo');
insert into "Photo" (user_id, photo_name) values (472, 'Wallaby, dama');
insert into "Photo" (user_id, photo_name) values (498, 'Sloth, pale-throated three-toed');
insert into "Photo" (user_id, photo_name) values (98, 'Galapagos tortoise');
insert into "Photo" (user_id, photo_name) values (952, 'Puku');
insert into "Photo" (user_id, photo_name) values (671, 'Wallaby, river');
insert into "Photo" (user_id, photo_name) values (845, 'Woolly-necked stork');
insert into "Photo" (user_id, photo_name) values (872, 'Olive baboon');
insert into "Photo" (user_id, photo_name) values (477, 'Grey lourie');
insert into "Photo" (user_id, photo_name) values (37, 'Camel, dromedary');
insert into "Photo" (user_id, photo_name) values (744, 'White-throated robin');
insert into "Photo" (user_id, photo_name) values (695, 'Collared lemming');
insert into "Photo" (user_id, photo_name) values (220, 'Pheasant, common');
insert into "Photo" (user_id, photo_name) values (309, 'Penguin, little blue');
insert into "Photo" (user_id, photo_name) values (993, 'Vulture, turkey');
insert into "Photo" (user_id, photo_name) values (763, 'Striped skunk');
insert into "Photo" (user_id, photo_name) values (255, 'African jacana');
insert into "Photo" (user_id, photo_name) values (297, 'Common duiker');
insert into "Photo" (user_id, photo_name) values (74, 'Gecko, barking');
insert into "Photo" (user_id, photo_name) values (855, 'Red-necked phalarope');
insert into "Photo" (user_id, photo_name) values (964, 'Common waterbuck');
insert into "Photo" (user_id, photo_name) values (553, 'Macaw, blue and gold');
insert into "Photo" (user_id, photo_name) values (77, 'Antelope, four-horned');
insert into "Photo" (user_id, photo_name) values (414, 'Bustard, kori');
insert into "Photo" (user_id, photo_name) values (287, 'Mara');
insert into "Photo" (user_id, photo_name) values (965, 'Plover, blacksmith');
insert into "Photo" (user_id, photo_name) values (935, 'Timber wolf');
insert into "Photo" (user_id, photo_name) values (177, 'Giraffe');
insert into "Photo" (user_id, photo_name) values (731, 'Black kite');
insert into "Photo" (user_id, photo_name) values (434, 'Grenadier, purple');
insert into "Photo" (user_id, photo_name) values (384, 'Otter, north american river');
insert into "Photo" (user_id, photo_name) values (140, 'Ring-necked pheasant');
insert into "Photo" (user_id, photo_name) values (894, 'Stick insect');
insert into "Photo" (user_id, photo_name) values (249, 'Hippopotamus');
insert into "Photo" (user_id, photo_name) values (388, 'Kangaroo, eastern grey');
insert into "Photo" (user_id, photo_name) values (168, 'White-browed owl');
insert into "Photo" (user_id, photo_name) values (851, 'Indian tree pie');
insert into "Photo" (user_id, photo_name) values (87, 'Heron, goliath');
insert into "Photo" (user_id, photo_name) values (435, 'Monkey, black spider');
insert into "Photo" (user_id, photo_name) values (784, 'Squirrel, nelson ground');
insert into "Photo" (user_id, photo_name) values (383, 'Spotted hyena');
insert into "Photo" (user_id, photo_name) values (702, 'African lion');
insert into "Photo" (user_id, photo_name) values (971, 'Tortoise, burmese black mountain');
insert into "Photo" (user_id, photo_name) values (97, 'Swamp deer');
insert into "Photo" (user_id, photo_name) values (409, 'Badger, eurasian');
insert into "Photo" (user_id, photo_name) values (569, 'Crow, house');
insert into "Photo" (user_id, photo_name) values (205, 'Squirrel, arctic ground');
insert into "Photo" (user_id, photo_name) values (436, 'Brown lemur');
insert into "Photo" (user_id, photo_name) values (191, 'Avocet, pied');
insert into "Photo" (user_id, photo_name) values (228, 'Oystercatcher, blackish');
insert into "Photo" (user_id, photo_name) values (179, 'Pheasant, common');
insert into "Photo" (user_id, photo_name) values (12, 'Trumpeter, green-winged');
insert into "Photo" (user_id, photo_name) values (680, 'Brown hyena');
insert into "Photo" (user_id, photo_name) values (797, 'Wallaroo, common');
insert into "Photo" (user_id, photo_name) values (331, 'Cat, ringtail');
insert into "Photo" (user_id, photo_name) values (975, 'Bottle-nose dolphin');
insert into "Photo" (user_id, photo_name) values (536, 'Mynah, common');
insert into "Photo" (user_id, photo_name) values (316, 'Boa, emerald green tree');
insert into "Photo" (user_id, photo_name) values (995, 'Lion, south american sea');
insert into "Photo" (user_id, photo_name) values (759, 'Trumpeter, green-winged');
insert into "Photo" (user_id, photo_name) values (934, 'Spur-winged goose');
insert into "Photo" (user_id, photo_name) values (981, 'Pine siskin');
insert into "Photo" (user_id, photo_name) values (373, 'Crane, black-crowned');
insert into "Photo" (user_id, photo_name) values (320, 'Coke''s hartebeest');
insert into "Photo" (user_id, photo_name) values (878, 'Denham''s bustard');
insert into "Photo" (user_id, photo_name) values (621, 'Common shelduck');
insert into "Photo" (user_id, photo_name) values (518, 'Civet cat');
insert into "Photo" (user_id, photo_name) values (791, 'Vulture, black');
insert into "Photo" (user_id, photo_name) values (713, 'Tortoise, galapagos');
insert into "Photo" (user_id, photo_name) values (984, 'Kori bustard');
insert into "Photo" (user_id, photo_name) values (957, 'White-winged tern');
insert into "Photo" (user_id, photo_name) values (454, 'Eastern white pelican');
insert into "Photo" (user_id, photo_name) values (914, 'Bee-eater (unidentified)');
insert into "Photo" (user_id, photo_name) values (682, 'Golden eagle');
insert into "Photo" (user_id, photo_name) values (299, 'Eleven-banded armadillo (unidentified)');
insert into "Photo" (user_id, photo_name) values (921, 'Helmeted guinea fowl');
insert into "Photo" (user_id, photo_name) values (749, 'Coyote');
insert into "Photo" (user_id, photo_name) values (443, 'Cape wild cat');
insert into "Photo" (user_id, photo_name) values (193, 'Devil, tasmanian');
insert into "Photo" (user_id, photo_name) values (443, 'Snake, racer');
insert into "Photo" (user_id, photo_name) values (217, 'Grison');
insert into "Photo" (user_id, photo_name) values (350, 'Peregrine falcon');
insert into "Photo" (user_id, photo_name) values (362, 'Thirteen-lined squirrel');
insert into "Photo" (user_id, photo_name) values (672, 'House sparrow');
insert into "Photo" (user_id, photo_name) values (430, 'Mouse, four-striped grass');
insert into "Photo" (user_id, photo_name) values (539, 'Civet (unidentified)');
insert into "Photo" (user_id, photo_name) values (763, 'Bear, polar');
insert into "Photo" (user_id, photo_name) values (598, 'Zorro, azara''s');
insert into "Photo" (user_id, photo_name) values (529, 'Glider, squirrel');
insert into "Photo" (user_id, photo_name) values (195, 'Lava gull');
insert into "Photo" (user_id, photo_name) values (294, 'Dragonfly, russian');
insert into "Photo" (user_id, photo_name) values (945, 'Kaffir cat');
insert into "Photo" (user_id, photo_name) values (289, 'Sugar glider');
insert into "Photo" (user_id, photo_name) values (707, 'Cat, european wild');
insert into "Photo" (user_id, photo_name) values (598, 'Brown capuchin');
insert into "Photo" (user_id, photo_name) values (102, 'Whip-tailed wallaby');
insert into "Photo" (user_id, photo_name) values (979, 'Bulbul, black-eyed');
insert into "Photo" (user_id, photo_name) values (127, 'Otter, african clawless');
insert into "Photo" (user_id, photo_name) values (283, 'Deer, red');
insert into "Photo" (user_id, photo_name) values (111, 'Kongoni');
insert into "Photo" (user_id, photo_name) values (81, 'Zebra, common');
insert into "Photo" (user_id, photo_name) values (584, 'Urial');
insert into "Photo" (user_id, photo_name) values (513, 'Campo flicker');
insert into "Photo" (user_id, photo_name) values (43, 'Bear, sloth');
insert into "Photo" (user_id, photo_name) values (990, 'Possum, ring-tailed');
insert into "Photo" (user_id, photo_name) values (893, 'Red-billed toucan');
insert into "Photo" (user_id, photo_name) values (634, 'Leopard');
insert into "Photo" (user_id, photo_name) values (491, 'Possum, pygmy');
insert into "Photo" (user_id, photo_name) values (868, 'Grey mouse lemur');
insert into "Photo" (user_id, photo_name) values (180, 'Quoll, eastern');
insert into "Photo" (user_id, photo_name) values (695, 'Dove, laughing');
insert into "Photo" (user_id, photo_name) values (828, 'Pigeon, wood');
insert into "Photo" (user_id, photo_name) values (159, 'Bahama pintail');
insert into "Photo" (user_id, photo_name) values (49, 'Cattle egret');
insert into "Photo" (user_id, photo_name) values (616, 'Otter, giant');
insert into "Photo" (user_id, photo_name) values (673, 'Cat, native');
insert into "Photo" (user_id, photo_name) values (21, 'Eagle owl (unidentified)');
insert into "Photo" (user_id, photo_name) values (350, 'Nutcracker, clark''s');
insert into "Photo" (user_id, photo_name) values (173, 'Least chipmunk');
insert into "Photo" (user_id, photo_name) values (605, 'Whip-tailed wallaby');
insert into "Photo" (user_id, photo_name) values (928, 'Four-spotted skimmer');
insert into "Photo" (user_id, photo_name) values (914, 'African elephant');
insert into "Photo" (user_id, photo_name) values (415, 'Sparrow, house');
insert into "Photo" (user_id, photo_name) values (769, 'Water monitor');
insert into "Photo" (user_id, photo_name) values (690, 'Peacock, blue');
insert into "Photo" (user_id, photo_name) values (751, 'Glider, feathertail');
insert into "Photo" (user_id, photo_name) values (438, 'Herring gull');
insert into "Photo" (user_id, photo_name) values (526, 'Ring-tailed gecko');
insert into "Photo" (user_id, photo_name) values (676, 'Pine siskin');
insert into "Photo" (user_id, photo_name) values (59, 'Knob-nosed goose');
insert into "Photo" (user_id, photo_name) values (53, 'Skimmer, four-spotted');
insert into "Photo" (user_id, photo_name) values (574, 'Rabbit, eastern cottontail');
insert into "Photo" (user_id, photo_name) values (941, 'Macaw, scarlet');
insert into "Photo" (user_id, photo_name) values (613, 'Common shelduck');
insert into "Photo" (user_id, photo_name) values (570, 'Fox, pampa gray');
insert into "Photo" (user_id, photo_name) values (194, 'Square-lipped rhinoceros');
insert into "Photo" (user_id, photo_name) values (449, 'African lynx');
insert into "Photo" (user_id, photo_name) values (844, 'Blacksmith plover');
insert into "Photo" (user_id, photo_name) values (838, 'Mongoose, javan gold-spotted');
insert into "Photo" (user_id, photo_name) values (71, 'Hanuman langur');
insert into "Photo" (user_id, photo_name) values (193, 'Baboon, gelada');
insert into "Photo" (user_id, photo_name) values (43, 'Caracara, yellow-headed');
insert into "Photo" (user_id, photo_name) values (489, 'Eagle, african fish');
insert into "Photo" (user_id, photo_name) values (743, 'Giant armadillo');
insert into "Photo" (user_id, photo_name) values (155, 'Vulture, turkey');
insert into "Photo" (user_id, photo_name) values (548, 'Lion, african');
insert into "Photo" (user_id, photo_name) values (499, 'Springhare');
insert into "Photo" (user_id, photo_name) values (561, 'Sloth, two-toed');
insert into "Photo" (user_id, photo_name) values (379, 'Bandicoot, long-nosed');
insert into "Photo" (user_id, photo_name) values (195, 'Buttermilk snake');
insert into "Photo" (user_id, photo_name) values (205, 'Weeper capuchin');
insert into "Photo" (user_id, photo_name) values (902, 'African ground squirrel (unidentified)');
insert into "Photo" (user_id, photo_name) values (84, 'Short-beaked echidna');
insert into "Photo" (user_id, photo_name) values (873, 'Deer, savannah');
insert into "Photo" (user_id, photo_name) values (617, 'Mandras tree shrew');
insert into "Photo" (user_id, photo_name) values (172, 'White-throated toucan');
insert into "Photo" (user_id, photo_name) values (514, 'Japanese macaque');
insert into "Photo" (user_id, photo_name) values (685, 'Gecko (unidentified)');
insert into "Photo" (user_id, photo_name) values (811, 'Caracara, yellow-headed');
insert into "Photo" (user_id, photo_name) values (402, 'Lapwing, southern');
insert into "Photo" (user_id, photo_name) values (66, 'Long-tailed jaeger');
insert into "Photo" (user_id, photo_name) values (729, 'Possum, western pygmy');
insert into "Photo" (user_id, photo_name) values (857, 'Vulture, lappet-faced');
insert into "Photo" (user_id, photo_name) values (723, 'Wallaby, tammar');
insert into "Photo" (user_id, photo_name) values (758, 'Ring-tailed coatimundi');
insert into "Photo" (user_id, photo_name) values (278, 'Oryx, fringe-eared');
insert into "Photo" (user_id, photo_name) values (65, 'Collared lemming');
insert into "Photo" (user_id, photo_name) values (861, 'Native cat');
insert into "Photo" (user_id, photo_name) values (86, 'Oystercatcher, blackish');
insert into "Photo" (user_id, photo_name) values (214, 'Turtle, long-necked');
insert into "Photo" (user_id, photo_name) values (16, 'Hornbill, yellow-billed');
insert into "Photo" (user_id, photo_name) values (534, 'Bat, little brown');
insert into "Photo" (user_id, photo_name) values (6, 'Guerza');
insert into "Photo" (user_id, photo_name) values (773, 'Glossy ibis');
insert into "Photo" (user_id, photo_name) values (652, 'Bandicoot, long-nosed');
insert into "Photo" (user_id, photo_name) values (560, 'Elephant, african');
insert into "Photo" (user_id, photo_name) values (399, 'Lion, mountain');
insert into "Photo" (user_id, photo_name) values (491, 'Bateleur eagle');
insert into "Photo" (user_id, photo_name) values (739, 'Crane, stanley');
insert into "Photo" (user_id, photo_name) values (523, 'Black-fronted bulbul');
insert into "Photo" (user_id, photo_name) values (626, 'Whale, baleen');
insert into "Photo" (user_id, photo_name) values (794, 'Baleen whale');
insert into "Photo" (user_id, photo_name) values (852, 'Crow, american');
insert into "Photo" (user_id, photo_name) values (82, 'Skink, blue-tongued');
insert into "Photo" (user_id, photo_name) values (746, 'African pied wagtail');
insert into "Photo" (user_id, photo_name) values (613, 'Jackal, golden');
insert into "Photo" (user_id, photo_name) values (27, 'Gecko (unidentified)');
insert into "Photo" (user_id, photo_name) values (641, 'Dolphin, striped');
insert into "Photo" (user_id, photo_name) values (104, 'Gerbil (unidentified)');
insert into "Photo" (user_id, photo_name) values (40, 'Monkey, vervet');
insert into "Photo" (user_id, photo_name) values (947, 'Blue crane');
insert into "Photo" (user_id, photo_name) values (413, 'Vulture, bengal');
insert into "Photo" (user_id, photo_name) values (546, 'Cougar');
insert into "Photo" (user_id, photo_name) values (677, 'Black-tailed tree creeper');
insert into "Photo" (user_id, photo_name) values (940, 'Woodchuck');
insert into "Photo" (user_id, photo_name) values (666, 'Striated heron');
insert into "Photo" (user_id, photo_name) values (88, 'Cat, civet');
insert into "Photo" (user_id, photo_name) values (512, 'Deer, red');
insert into "Photo" (user_id, photo_name) values (492, 'Long-tailed spotted cat');
insert into "Photo" (user_id, photo_name) values (173, 'Groundhog');
insert into "Photo" (user_id, photo_name) values (628, 'Dragonfly, russian');
insert into "Photo" (user_id, photo_name) values (368, 'Dove, rock');
insert into "Photo" (user_id, photo_name) values (823, 'Blue and yellow macaw');
insert into "Photo" (user_id, photo_name) values (170, 'Bee-eater, carmine');
insert into "Photo" (user_id, photo_name) values (203, 'Water moccasin');
insert into "Photo" (user_id, photo_name) values (360, 'American buffalo');
insert into "Photo" (user_id, photo_name) values (264, 'Eagle, pallas''s fish');
insert into "Photo" (user_id, photo_name) values (356, 'Elegant crested tinamou');
insert into "Photo" (user_id, photo_name) values (128, 'Hoary marmot');
insert into "Photo" (user_id, photo_name) values (199, 'Greater blue-eared starling');
insert into "Photo" (user_id, photo_name) values (275, 'Violet-eared waxbill');
insert into "Photo" (user_id, photo_name) values (445, 'Meerkat');
insert into "Photo" (user_id, photo_name) values (1, 'Teal, hottentot');
insert into "Photo" (user_id, photo_name) values (970, 'Brazilian otter');
insert into "Photo" (user_id, photo_name) values (392, 'African jacana');
insert into "Photo" (user_id, photo_name) values (576, 'Kafue flats lechwe');
insert into "Photo" (user_id, photo_name) values (795, 'Praying mantis (unidentified)');
insert into "Photo" (user_id, photo_name) values (908, 'Gecko (unidentified)');
insert into "Photo" (user_id, photo_name) values (692, 'White rhinoceros');
insert into "Photo" (user_id, photo_name) values (661, 'Lesser double-collared sunbird');
insert into "Photo" (user_id, photo_name) values (67, 'Springhare');
insert into "Photo" (user_id, photo_name) values (168, 'Small-spotted genet');
insert into "Photo" (user_id, photo_name) values (644, 'Thrasher, curve-billed');
insert into "Photo" (user_id, photo_name) values (578, 'Raccoon dog');
insert into "Photo" (user_id, photo_name) values (138, 'Tern, royal');
insert into "Photo" (user_id, photo_name) values (958, 'Hoffman''s sloth');
insert into "Photo" (user_id, photo_name) values (101, 'Macaw, blue and yellow');
insert into "Photo" (user_id, photo_name) values (525, 'Mongoose, javan gold-spotted');
insert into "Photo" (user_id, photo_name) values (160, 'Chilean flamingo');
insert into "Photo" (user_id, photo_name) values (263, 'Red-capped cardinal');
insert into "Photo" (user_id, photo_name) values (675, 'Mongoose, javan gold-spotted');
insert into "Photo" (user_id, photo_name) values (470, 'Lion, mountain');
insert into "Photo" (user_id, photo_name) values (412, 'Monkey, bleeding heart');
insert into "Photo" (user_id, photo_name) values (453, 'African fish eagle');
insert into "Photo" (user_id, photo_name) values (384, 'Civet (unidentified)');
insert into "Photo" (user_id, photo_name) values (412, 'Sparrow, house');
insert into "Photo" (user_id, photo_name) values (616, 'Elephant, asian');
insert into "Photo" (user_id, photo_name) values (434, 'Camel, dromedary');
insert into "Photo" (user_id, photo_name) values (301, 'Barbet, levaillant''s');
insert into "Photo" (user_id, photo_name) values (942, 'Duiker, common');
insert into "Photo" (user_id, photo_name) values (853, 'Devil, tasmanian');
insert into "Photo" (user_id, photo_name) values (814, 'Vicuna');
insert into "Photo" (user_id, photo_name) values (450, 'Bleu, red-cheeked cordon');
insert into "Photo" (user_id, photo_name) values (804, 'Buffalo, american');
insert into "Photo" (user_id, photo_name) values (246, 'Common dolphin');
insert into "Photo" (user_id, photo_name) values (307, 'Steenbuck');
insert into "Photo" (user_id, photo_name) values (423, 'Cape fox');
insert into "Photo" (user_id, photo_name) values (813, 'Goose, egyptian');
insert into "Photo" (user_id, photo_name) values (555, 'Dove, laughing');
insert into "Photo" (user_id, photo_name) values (27, 'Vulture, oriental white-backed');
insert into "Photo" (user_id, photo_name) values (763, 'Sloth, two-toed');
insert into "Photo" (user_id, photo_name) values (187, 'Gull, pacific');
insert into "Photo" (user_id, photo_name) values (831, 'Ground legaan');
insert into "Photo" (user_id, photo_name) values (823, 'Gonolek, burchell''s');
insert into "Photo" (user_id, photo_name) values (808, 'Indian giant squirrel');
insert into "Photo" (user_id, photo_name) values (787, 'Neotropic cormorant');
insert into "Photo" (user_id, photo_name) values (930, 'Tiger cat');
insert into "Photo" (user_id, photo_name) values (960, 'Ring dove');
insert into "Photo" (user_id, photo_name) values (336, 'Eurasian hoopoe');
insert into "Photo" (user_id, photo_name) values (435, 'Possum, pygmy');
insert into "Photo" (user_id, photo_name) values (169, 'Cape fox');
insert into "Photo" (user_id, photo_name) values (159, 'Grey heron');
insert into "Photo" (user_id, photo_name) values (907, 'Langur, common');
insert into "Photo" (user_id, photo_name) values (910, 'Porcupine, north american');
insert into "Photo" (user_id, photo_name) values (897, 'Sage grouse');
insert into "Photo" (user_id, photo_name) values (274, 'Japanese macaque');
insert into "Photo" (user_id, photo_name) values (393, 'Dove, galapagos');
insert into "Photo" (user_id, photo_name) values (230, 'Southern lapwing');
insert into "Photo" (user_id, photo_name) values (712, 'Coatimundi, ring-tailed');
insert into "Photo" (user_id, photo_name) values (564, 'Black-collared barbet');
insert into "Photo" (user_id, photo_name) values (317, 'Eastern dwarf mongoose');
insert into "Photo" (user_id, photo_name) values (227, 'Brown antechinus');
insert into "Photo" (user_id, photo_name) values (106, 'Goose, knob-nosed');
insert into "Photo" (user_id, photo_name) values (143, 'Black-tailed prairie dog');
insert into "Photo" (user_id, photo_name) values (253, 'Darter, african');
insert into "Photo" (user_id, photo_name) values (153, 'Cheetah');
insert into "Photo" (user_id, photo_name) values (944, 'Asiatic jackal');
insert into "Photo" (user_id, photo_name) values (865, 'African pied wagtail');
insert into "Photo" (user_id, photo_name) values (335, 'Indian peacock');
insert into "Photo" (user_id, photo_name) values (434, 'Oriental white-backed vulture');
insert into "Photo" (user_id, photo_name) values (438, 'Lorikeet, scaly-breasted');
insert into "Photo" (user_id, photo_name) values (765, 'Common turkey');
insert into "Photo" (user_id, photo_name) values (268, 'Whale, killer');
insert into "Photo" (user_id, photo_name) values (561, 'Albatross, waved');
insert into "Photo" (user_id, photo_name) values (411, 'Desert kangaroo rat');
insert into "Photo" (user_id, photo_name) values (493, 'Hawk-headed parrot');
insert into "Photo" (user_id, photo_name) values (666, 'Blue-faced booby');
insert into "Photo" (user_id, photo_name) values (472, 'Savanna fox');
insert into "Photo" (user_id, photo_name) values (712, 'Ox, musk');
insert into "Photo" (user_id, photo_name) values (763, 'European shelduck');
insert into "Photo" (user_id, photo_name) values (262, 'Golden brush-tailed possum');
insert into "Photo" (user_id, photo_name) values (567, 'Dog, bush');
insert into "Photo" (user_id, photo_name) values (346, 'Common seal');
insert into "Photo" (user_id, photo_name) values (976, 'Asian red fox');
insert into "Photo" (user_id, photo_name) values (236, 'Sable antelope');
insert into "Photo" (user_id, photo_name) values (699, 'Gecko, ring-tailed');
insert into "Photo" (user_id, photo_name) values (40, 'Pygmy possum');
insert into "Photo" (user_id, photo_name) values (399, 'Groundhog');
insert into "Photo" (user_id, photo_name) values (955, 'Eagle, white-bellied sea');
insert into "Photo" (user_id, photo_name) values (656, 'Butterfly (unidentified)');
insert into "Photo" (user_id, photo_name) values (140, 'Western lowland gorilla');
insert into "Photo" (user_id, photo_name) values (540, 'Heron, green');
insert into "Photo" (user_id, photo_name) values (581, 'Gila monster');
insert into "Photo" (user_id, photo_name) values (222, 'Long-tailed jaeger');
insert into "Photo" (user_id, photo_name) values (543, 'Dolphin, striped');
insert into "Photo" (user_id, photo_name) values (308, 'Sheep, red');
insert into "Photo" (user_id, photo_name) values (911, 'Goose, snow');
insert into "Photo" (user_id, photo_name) values (544, 'Skunk, striped');
insert into "Photo" (user_id, photo_name) values (399, 'Smith''s bush squirrel');
insert into "Photo" (user_id, photo_name) values (580, 'Sulfur-crested cockatoo');
insert into "Photo" (user_id, photo_name) values (878, 'Pied avocet');
insert into "Photo" (user_id, photo_name) values (134, 'Baboon, olive');
insert into "Photo" (user_id, photo_name) values (333, 'Downy woodpecker');
insert into "Photo" (user_id, photo_name) values (860, 'Devil, tasmanian');
insert into "Photo" (user_id, photo_name) values (988, 'Owl, snowy');
insert into "Photo" (user_id, photo_name) values (277, 'Cattle egret');
insert into "Photo" (user_id, photo_name) values (239, 'Butterfly, canadian tiger swallowtail');
insert into "Photo" (user_id, photo_name) values (958, 'Wood pigeon');
insert into "Photo" (user_id, photo_name) values (41, 'Huron');
insert into "Photo" (user_id, photo_name) values (546, 'Lion, african');
insert into "Photo" (user_id, photo_name) values (431, 'Blackbuck');
insert into "Photo" (user_id, photo_name) values (378, 'Wallaby, whip-tailed');
insert into "Photo" (user_id, photo_name) values (430, 'Cardinal, black-throated');
insert into "Photo" (user_id, photo_name) values (499, 'Tern, royal');
insert into "Photo" (user_id, photo_name) values (482, 'Tayra');
insert into "Photo" (user_id, photo_name) values (53, 'Red deer');
insert into "Photo" (user_id, photo_name) values (215, 'Tern, white-winged black');
insert into "Photo" (user_id, photo_name) values (951, 'Carpet python');
insert into "Photo" (user_id, photo_name) values (458, 'Japanese macaque');
insert into "Photo" (user_id, photo_name) values (752, 'Leadbeateri''s ground hornbill');
insert into "Photo" (user_id, photo_name) values (257, 'Raven, cape');
insert into "Photo" (user_id, photo_name) values (152, 'White-mantled colobus');
insert into "Photo" (user_id, photo_name) values (282, 'Gulls (unidentified)');
insert into "Photo" (user_id, photo_name) values (886, 'Stork, painted');
insert into "Photo" (user_id, photo_name) values (425, 'Hornbill, leadbeateri''s ground');
insert into "Photo" (user_id, photo_name) values (515, 'Wallaby, river');
insert into "Photo" (user_id, photo_name) values (789, 'Fox, asian red');
insert into "Photo" (user_id, photo_name) values (792, 'Marmot, hoary');
insert into "Photo" (user_id, photo_name) values (253, 'Gaur');
insert into "Photo" (user_id, photo_name) values (315, 'Crab-eating raccoon');
insert into "Photo" (user_id, photo_name) values (833, 'Fox, pampa gray');
insert into "Photo" (user_id, photo_name) values (620, 'Pelican, great white');
insert into "Photo" (user_id, photo_name) values (785, 'Hen, sage');
insert into "Photo" (user_id, photo_name) values (903, 'Rhea, greater');
insert into "Photo" (user_id, photo_name) values (843, 'Toucan, red-billed');
insert into "Photo" (user_id, photo_name) values (891, 'Tawny eagle');
insert into "Photo" (user_id, photo_name) values (880, 'Blue fox');
insert into "Photo" (user_id, photo_name) values (62, 'Ovenbird');
insert into "Photo" (user_id, photo_name) values (416, 'Old world fruit bat (unidentified)');
insert into "Photo" (user_id, photo_name) values (341, 'Cat, civet');
insert into "Photo" (user_id, photo_name) values (763, 'Porcupine, prehensile-tailed');
insert into "Photo" (user_id, photo_name) values (441, 'Goose, andean');
insert into "Photo" (user_id, photo_name) values (900, 'Gerenuk');
insert into "Photo" (user_id, photo_name) values (822, 'Barrows goldeneye');
insert into "Photo" (user_id, photo_name) values (172, 'Desert tortoise');
insert into "Photo" (user_id, photo_name) values (460, 'Spoonbill, european');
insert into "Photo" (user_id, photo_name) values (440, 'Pie, indian tree');
insert into "Photo" (user_id, photo_name) values (218, 'Giraffe');
insert into "Photo" (user_id, photo_name) values (882, 'Barrows goldeneye');
insert into "Photo" (user_id, photo_name) values (273, 'Mountain duck');
insert into "Photo" (user_id, photo_name) values (333, 'Siskin, yellow-rumped');
insert into "Photo" (user_id, photo_name) values (366, 'Sheathbill, snowy');
insert into "Photo" (user_id, photo_name) values (88, 'Southern brown bandicoot');
insert into "Photo" (user_id, photo_name) values (1, 'Purple grenadier');
insert into "Photo" (user_id, photo_name) values (136, 'Red-tailed wambenger');
insert into "Photo" (user_id, photo_name) values (924, 'Bandicoot, long-nosed');
insert into "Photo" (user_id, photo_name) values (860, 'Mouflon');
insert into "Photo" (user_id, photo_name) values (93, 'Arctic tern');
insert into "Photo" (user_id, photo_name) values (946, 'Sparrow, house');
insert into "Photo" (user_id, photo_name) values (423, 'Striped hyena');
insert into "Photo" (user_id, photo_name) values (181, 'Desert tortoise');
insert into "Photo" (user_id, photo_name) values (127, 'American marten');
insert into "Photo" (user_id, photo_name) values (909, 'Asian red fox');
insert into "Photo" (user_id, photo_name) values (96, 'Catfish, blue');
insert into "Photo" (user_id, photo_name) values (677, 'Cuis');
insert into "Photo" (user_id, photo_name) values (636, 'Raccoon dog');
insert into "Photo" (user_id, photo_name) values (842, 'European red squirrel');
insert into "Photo" (user_id, photo_name) values (106, 'Kangaroo, red');
insert into "Photo" (user_id, photo_name) values (915, 'Hummingbird (unidentified)');
insert into "Photo" (user_id, photo_name) values (957, 'Flightless cormorant');
insert into "Photo" (user_id, photo_name) values (329, 'Goliath heron');
insert into "Photo" (user_id, photo_name) values (274, 'Beaver, north american');
insert into "Photo" (user_id, photo_name) values (696, 'Leopard, indian');
insert into "Photo" (user_id, photo_name) values (240, 'Plover, three-banded');
insert into "Photo" (user_id, photo_name) values (266, 'Dassie');
insert into "Photo" (user_id, photo_name) values (643, 'Banded mongoose');
insert into "Photo" (user_id, photo_name) values (985, 'Red-tailed cockatoo');
insert into "Photo" (user_id, photo_name) values (445, 'Cheetah');
insert into "Photo" (user_id, photo_name) values (512, 'Weeper capuchin');
insert into "Photo" (user_id, photo_name) values (82, 'Long-finned pilot whale');
insert into "Photo" (user_id, photo_name) values (623, 'Vulture, bengal');
insert into "Photo" (user_id, photo_name) values (187, 'Buffalo, african');
insert into "Photo" (user_id, photo_name) values (399, 'Cape white-eye');
insert into "Photo" (user_id, photo_name) values (820, 'Blue fox');
insert into "Photo" (user_id, photo_name) values (653, 'Cape Barren goose');
insert into "Photo" (user_id, photo_name) values (265, 'Verreaux''s sifaka');
insert into "Photo" (user_id, photo_name) values (227, 'Cormorant, flightless');
insert into "Photo" (user_id, photo_name) values (402, 'American buffalo');
insert into "Photo" (user_id, photo_name) values (536, 'Moccasin, water');
insert into "Photo" (user_id, photo_name) values (652, 'Hawk, red-tailed');
insert into "Photo" (user_id, photo_name) values (783, 'White-throated kingfisher');
insert into "Photo" (user_id, photo_name) values (828, 'Warthog');
insert into "Photo" (user_id, photo_name) values (783, 'Netted rock dragon');
insert into "Photo" (user_id, photo_name) values (466, 'Bee-eater (unidentified)');
insert into "Photo" (user_id, photo_name) values (17, 'Arctic hare');
insert into "Photo" (user_id, photo_name) values (990, 'Woodchuck');
insert into "Photo" (user_id, photo_name) values (161, 'Fringe-eared oryx');
insert into "Photo" (user_id, photo_name) values (813, 'Armadillo, seven-banded');
insert into "Photo" (user_id, photo_name) values (312, 'Stork, marabou');
insert into "Photo" (user_id, photo_name) values (578, 'Monkey, vervet');
insert into "Photo" (user_id, photo_name) values (372, 'Phascogale, brush-tailed');
insert into "Photo" (user_id, photo_name) values (136, 'Rock dove');
insert into "Photo" (user_id, photo_name) values (18, 'Agama lizard (unidentified)');
insert into "Photo" (user_id, photo_name) values (731, 'Ibis, puna');
insert into "Photo" (user_id, photo_name) values (319, 'Squirrel, malabar');
insert into "Photo" (user_id, photo_name) values (327, 'Tawny frogmouth');
insert into "Photo" (user_id, photo_name) values (889, 'North American river otter');
insert into "Photo" (user_id, photo_name) values (978, 'Antelope ground squirrel');
insert into "Photo" (user_id, photo_name) values (434, 'Small-spotted genet');
insert into "Photo" (user_id, photo_name) values (575, 'Lemur, grey mouse');
insert into "Photo" (user_id, photo_name) values (355, 'Stick insect');
insert into "Photo" (user_id, photo_name) values (456, 'Fowl, helmeted guinea');
insert into "Photo" (user_id, photo_name) values (424, 'Red-billed tropic bird');
insert into "Photo" (user_id, photo_name) values (453, 'Macaw, blue and gold');
insert into "Photo" (user_id, photo_name) values (968, 'White-fronted bee-eater');
insert into "Photo" (user_id, photo_name) values (861, 'Otter, cape clawless');
insert into "Photo" (user_id, photo_name) values (913, 'Long-nosed bandicoot');
insert into "Photo" (user_id, photo_name) values (319, 'Stork, european');
insert into "Photo" (user_id, photo_name) values (299, 'Bunting, crested');
insert into "Photo" (user_id, photo_name) values (504, 'Salmon pink bird eater tarantula');
insert into "Photo" (user_id, photo_name) values (117, 'African pied wagtail');
insert into "Photo" (user_id, photo_name) values (904, 'Northern phalarope');
insert into "Photo" (user_id, photo_name) values (705, 'Scaly-breasted lorikeet');
insert into "Photo" (user_id, photo_name) values (547, 'Barbet, black-collared');
insert into "Photo" (user_id, photo_name) values (345, 'Black-tailed tree creeper');
insert into "Photo" (user_id, photo_name) values (602, 'Pintail, white-cheeked');
insert into "Photo" (user_id, photo_name) values (158, 'African porcupine');
insert into "Photo" (user_id, photo_name) values (936, 'Snake, carpet');
insert into "Photo" (user_id, photo_name) values (814, 'Lion, australian sea');
insert into "Photo" (user_id, photo_name) values (198, 'Bee-eater, carmine');
insert into "Photo" (user_id, photo_name) values (432, 'Otter, small-clawed');
insert into "Photo" (user_id, photo_name) values (856, 'Golden eagle');
insert into "Photo" (user_id, photo_name) values (746, 'Mongoose, small indian');
insert into "Photo" (user_id, photo_name) values (642, 'Gnu, brindled');
insert into "Photo" (user_id, photo_name) values (632, 'Wildebeest, blue');
insert into "Photo" (user_id, photo_name) values (769, 'Emerald-spotted wood dove');
insert into "Photo" (user_id, photo_name) values (514, 'Japanese macaque');
insert into "Photo" (user_id, photo_name) values (171, 'Civet, small-toothed palm');
insert into "Photo" (user_id, photo_name) values (39, 'Field flicker');
insert into "Photo" (user_id, photo_name) values (258, 'Osprey');
insert into "Photo" (user_id, photo_name) values (969, 'Mountain duck');
insert into "Photo" (user_id, photo_name) values (952, 'Short-nosed bandicoot');
insert into "Photo" (user_id, photo_name) values (111, 'Eagle, bald');
insert into "Photo" (user_id, photo_name) values (145, 'Chimpanzee');
insert into "Photo" (user_id, photo_name) values (2, 'Cobra, egyptian');
insert into "Photo" (user_id, photo_name) values (612, 'Sun gazer');
insert into "Photo" (user_id, photo_name) values (13, 'Ornate rock dragon');
insert into "Photo" (user_id, photo_name) values (854, 'Goose, cape barren');
insert into "Photo" (user_id, photo_name) values (77, 'Sloth, hoffman''s');
insert into "Photo" (user_id, photo_name) values (35, 'Yellow-headed caracara');
insert into "Photo" (user_id, photo_name) values (88, 'Parakeet, rose-ringed');
insert into "Photo" (user_id, photo_name) values (513, 'Flycatcher, tyrant');
insert into "Photo" (user_id, photo_name) values (301, 'Red howler monkey');
insert into "Photo" (user_id, photo_name) values (8, 'Glider, sugar');
insert into "Photo" (user_id, photo_name) values (539, 'Springbok');
insert into "Photo" (user_id, photo_name) values (800, 'Javanese cormorant');
insert into "Photo" (user_id, photo_name) values (426, 'Oribi');
insert into "Photo" (user_id, photo_name) values (453, 'Common eland');
insert into "Photo" (user_id, photo_name) values (163, 'Fairy penguin');
insert into "Photo" (user_id, photo_name) values (389, 'Red and blue macaw');
insert into "Photo" (user_id, photo_name) values (614, 'Shrike, crimson-breasted');
insert into "Photo" (user_id, photo_name) values (24, 'Viper, egyptian');
insert into "Photo" (user_id, photo_name) values (568, 'Cliffchat, mocking');
insert into "Photo" (user_id, photo_name) values (569, 'Seal, common');
insert into "Photo" (user_id, photo_name) values (761, 'White-fronted capuchin');
insert into "Photo" (user_id, photo_name) values (597, 'Wolf spider');
insert into "Photo" (user_id, photo_name) values (210, 'Phalarope, grey');
insert into "Photo" (user_id, photo_name) values (39, 'Wallaby, tammar');
insert into "Photo" (user_id, photo_name) values (750, 'Swainson''s francolin');
insert into "Photo" (user_id, photo_name) values (124, 'Brown antechinus');
insert into "Photo" (user_id, photo_name) values (489, 'Little heron');
insert into "Photo" (user_id, photo_name) values (867, 'Fowl, helmeted guinea');
insert into "Photo" (user_id, photo_name) values (911, 'Echidna, short-beaked');
insert into "Photo" (user_id, photo_name) values (677, 'Dragon, komodo');
insert into "Photo" (user_id, photo_name) values (393, 'African bush squirrel');
insert into "Photo" (user_id, photo_name) values (39, 'Barasingha deer');
insert into "Photo" (user_id, photo_name) values (423, 'Partridge, coqui');
insert into "Photo" (user_id, photo_name) values (372, 'Cockatoo, roseate');
insert into "Photo" (user_id, photo_name) values (942, 'Greater kudu');
insert into "Photo" (user_id, photo_name) values (241, 'Alligator, american');
insert into "Photo" (user_id, photo_name) values (806, 'White-lipped peccary');
insert into "Photo" (user_id, photo_name) values (990, 'Striped hyena');
insert into "Photo" (user_id, photo_name) values (491, 'Eastern box turtle');
insert into "Photo" (user_id, photo_name) values (252, 'Hen, sage');
insert into "Photo" (user_id, photo_name) values (749, 'Long-tailed jaeger');
insert into "Photo" (user_id, photo_name) values (205, 'Gazelle, grant''s');
insert into "Photo" (user_id, photo_name) values (144, 'Stork, greater adjutant');
insert into "Photo" (user_id, photo_name) values (335, 'Yellow-bellied marmot');
insert into "Photo" (user_id, photo_name) values (447, 'Mongoose, small indian');
insert into "Photo" (user_id, photo_name) values (893, 'Bohor reedbuck');
insert into "Photo" (user_id, photo_name) values (710, 'Australian spiny anteater');
insert into "Photo" (user_id, photo_name) values (654, 'Eland, common');
insert into "Photo" (user_id, photo_name) values (601, 'Campo flicker');
insert into "Photo" (user_id, photo_name) values (439, 'Steenbuck');
insert into "Photo" (user_id, photo_name) values (559, 'Hen, sage');
insert into "Photo" (user_id, photo_name) values (255, 'Penguin, magellanic');
insert into "Photo" (user_id, photo_name) values (102, 'Cat, native');
insert into "Photo" (user_id, photo_name) values (818, 'European wild cat');
insert into "Photo" (user_id, photo_name) values (562, 'Brindled gnu');
insert into "Photo" (user_id, photo_name) values (71, 'Worm snake (unidentified)');
insert into "Photo" (user_id, photo_name) values (665, 'Black rhinoceros');
insert into "Photo" (user_id, photo_name) values (91, 'Green-winged macaw');
insert into "Photo" (user_id, photo_name) values (228, 'Killer whale');
insert into "Photo" (user_id, photo_name) values (252, 'Kingfisher, pied');
insert into "Photo" (user_id, photo_name) values (33, 'Cuis');
insert into "Photo" (user_id, photo_name) values (240, 'Southern brown bandicoot');
insert into "Photo" (user_id, photo_name) values (398, 'Albatross, waved');
insert into "Photo" (user_id, photo_name) values (998, 'Bushpig');
insert into "Photo" (user_id, photo_name) values (357, 'Little grebe');
insert into "Photo" (user_id, photo_name) values (380, 'Siskin, yellow-rumped');
insert into "Photo" (user_id, photo_name) values (663, 'California sea lion');
insert into "Photo" (user_id, photo_name) values (738, 'Devil, tasmanian');
insert into "Photo" (user_id, photo_name) values (397, 'Wolf, mexican');
insert into "Photo" (user_id, photo_name) values (937, 'Vine snake (unidentified)');
insert into "Photo" (user_id, photo_name) values (355, 'Gull, lava');
insert into "Photo" (user_id, photo_name) values (55, 'Blue crane');
insert into "Photo" (user_id, photo_name) values (559, 'Possum, pygmy');
insert into "Photo" (user_id, photo_name) values (434, 'Common pheasant');
insert into "Photo" (user_id, photo_name) values (841, 'Southern ground hornbill');
insert into "Photo" (user_id, photo_name) values (982, 'Verreaux''s sifaka');
insert into "Photo" (user_id, photo_name) values (219, 'Rhinoceros, black');
insert into "Photo" (user_id, photo_name) values (306, 'Mara');
insert into "Photo" (user_id, photo_name) values (292, 'Armadillo, seven-banded');
insert into "Photo" (user_id, photo_name) values (507, 'Darter, african');
insert into "Photo" (user_id, photo_name) values (435, 'Skink, blue-tongued');
insert into "Photo" (user_id, photo_name) values (693, 'Tiger cat');
insert into "Photo" (user_id, photo_name) values (508, 'Creeper, black-tailed tree');
insert into "Photo" (user_id, photo_name) values (624, 'Crane, blue');
insert into "Photo" (user_id, photo_name) values (450, 'Marmot, yellow-bellied');
insert into "Photo" (user_id, photo_name) values (744, 'Fisher');
insert into "Photo" (user_id, photo_name) values (278, 'Goose, snow');
insert into "Photo" (user_id, photo_name) values (753, 'Silver-backed jackal');
insert into "Photo" (user_id, photo_name) values (117, 'Darter, african');
insert into "Photo" (user_id, photo_name) values (717, 'Javanese cormorant');
insert into "Photo" (user_id, photo_name) values (692, 'Brown pelican');
insert into "Photo" (user_id, photo_name) values (525, 'Cattle egret');
insert into "Photo" (user_id, photo_name) values (327, 'Red-tailed cockatoo');
insert into "Photo" (user_id, photo_name) values (744, 'Crow, house');
insert into "Photo" (user_id, photo_name) values (489, 'Sally lightfoot crab');
insert into "Photo" (user_id, photo_name) values (888, 'Paddy heron (unidentified)');
insert into "Photo" (user_id, photo_name) values (257, 'Tarantula, salmon pink bird eater');
insert into "Photo" (user_id, photo_name) values (649, 'Asian elephant');
insert into "Photo" (user_id, photo_name) values (958, 'Racer, american');
insert into "Photo" (user_id, photo_name) values (314, 'Lesser flamingo');
insert into "Photo" (user_id, photo_name) values (564, 'Pallas''s fish eagle');
insert into "Photo" (user_id, photo_name) values (528, 'Mongoose, small indian');
insert into "Photo" (user_id, photo_name) values (417, 'Dog, raccoon');
insert into "Photo" (user_id, photo_name) values (901, 'Goose, greylag');
insert into "Photo" (user_id, photo_name) values (14, 'Squirrel, thirteen-lined');
insert into "Photo" (user_id, photo_name) values (285, 'Tern, arctic');
insert into "Photo" (user_id, photo_name) values (594, 'Snake, western patch-nosed');
insert into "Photo" (user_id, photo_name) values (530, 'American bighorn sheep');
insert into "Photo" (user_id, photo_name) values (54, 'Boa, columbian rainbow');
insert into "Photo" (user_id, photo_name) values (197, 'European spoonbill');
insert into "Photo" (user_id, photo_name) values (561, 'Stork, woolly-necked');
insert into "Photo" (user_id, photo_name) values (706, 'Small-toothed palm civet');
insert into "Photo" (user_id, photo_name) values (923, 'Heron, boat-billed');
insert into "Photo" (user_id, photo_name) values (519, 'Horned rattlesnake');
insert into "Photo" (user_id, photo_name) values (433, 'Stanley bustard');
insert into "Photo" (user_id, photo_name) values (185, 'Bulbul, black-fronted');
